arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: l10n.dart
output-class: S
preferred-supported-locales: [en, tr]
use-deferred-loading: false

# Yeni string ekle
viewFullHistory: "View Full History" 