// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDA5GXNpmaE0iwYV_Kl6KbfP1XJ1kl3OE',
    appId: '1:525388301988:web:45a07908e2ec938ae6c831',
    messagingSenderId: '525388301988',
    projectId: 'maskoff-7179e',
    authDomain: 'maskoff-7179e.firebaseapp.com',
    storageBucket: 'maskoff-7179e.firebasestorage.app',
    measurementId: 'G-XT79HV43YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWHqI4MYtwVqBzm1MPJwTn0FGvVgZLNBg',
    appId: '1:525388301988:android:d952209a7d4862ebe6c831',
    messagingSenderId: '525388301988',
    projectId: 'maskoff-7179e',
    storageBucket: 'maskoff-7179e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFoHtHE_ckoy7r2BX_odAk-VmKoTG1rPk',
    appId: '1:525388301988:ios:89a699b29d8afe35e6c831',
    messagingSenderId: '525388301988',
    projectId: 'maskoff-7179e',
    storageBucket: 'maskoff-7179e.firebasestorage.app',
    iosBundleId: 'com.example.testvid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFoHtHE_ckoy7r2BX_odAk-VmKoTG1rPk',
    appId: '1:525388301988:ios:89a699b29d8afe35e6c831',
    messagingSenderId: '525388301988',
    projectId: 'maskoff-7179e',
    storageBucket: 'maskoff-7179e.firebasestorage.app',
    iosBundleId: 'com.example.testvid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDA5GXNpmaE0iwYV_Kl6KbfP1XJ1kl3OE',
    appId: '1:525388301988:web:a93e7ae2e88942a7e6c831',
    messagingSenderId: '525388301988',
    projectId: 'maskoff-7179e',
    authDomain: 'maskoff-7179e.firebaseapp.com',
    storageBucket: 'maskoff-7179e.firebasestorage.app',
    measurementId: 'G-VH6RQYD8GJ',
  );
}
